name: Update BigCommerce Theme with Bolt

description: >
  GitHub Action that updates a BigCommerce theme repository as described in Step 6 of the Bolt BigCommerce installation guide.

author: bolt

inputs:
  theme_directory:
    description: "Path to the BigCommerce theme directory to update (e.g., ./theme)"
    required: false
    default: "./theme"

  output_directory:
    description: "Directory to save the modified theme"
    required: false
    default: "./bolt-modified-theme"

  publishable_key:
    description: "Bolt publishable key"
    required: true

  environment:
    description: "Bolt environment: production or sandbox"
    required: false
    default: "production"

  theme_name:
    description: "Name for the modified theme"
    required: false
    default: "Bolt-Modified-Theme"

  route_token:
    description: "Route shipping insurance token (optional)"
    required: false

  openai_api_key:
    description: "Your OpenAI API key (for AI-assisted modifications)"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.theme_directory }}
    - ${{ inputs.output_directory }}
    - ${{ inputs.publishable_key }}
    - ${{ inputs.environment }}
    - ${{ inputs.theme_name }}
    - ${{ inputs.route_token }}
    - ${{ inputs.openai_api_key }}
